---
title: "Academic and Professional Experience"
output: html_document
---
<br>

## EDUCATION	 
**Columbia University Mailman School of Public Health, New York, NY May 2020** <br>
Master of Public Health (MPH) in Epidemiology, Certificate in Applied Biostatistics                                                             

**Coursework:** Applied Regression I & II, Data Science I & II, Analysis of Categorical Data, Epidemiology 3: Applied Epidemiologic Analysis, Cancer Epidemiology, Relational Databases and SQL Programming

**The George Washington University Milken Institute School of Public Health, Washington, D.C. May 2017** <br>
Bachelor of Science (BS), Double Major in Public Health and Biology                                                                                 
<br>

## WORK EXPERIENCE 
**Columbia University Mailman School of Public Health, New York, NY January 2020-May2020** <br>
_Graduate Teaching Assistant_ <br>
• Teaching Assistant for Relational Databases and SQL Programming for Research and Data Science, taught to 40 graduate students <br>
• Helps students understand how to design relational databases and to write queries using the SQL programming language <br>

**New York City Department of Health and Mental Hygiene, New York, NY  April 2019–April 2020** <br>
_Disease Control Intern, Division of Disease Control, Bureau of Communicable Disease_ <br>
•	Conducts infectious disease surveillance and leads cluster investigations for Salmonellosis cases within New York City <br>
•	Collects case data from health care providers and administers phone interviews with case-patients to determine outbreak etiology <br>
•	Creates weekly reports of local clusters of Salmonella isolates using whole genome sequencing results in BioNumerics <br>
• Performs statistical analyses in SAS and utilizes epidemiological techniques to determine causality between linked cases 

**Columbia University School of Nursing, New York, NY February 2019–Present ** <br>
_Research Assistant_ <br>
•	Conducts data analyses on dataset containing over 10,000 observations in SAS to examine the relationship between nurse staffing and unit-based hospital-acquired infection scores within 4 New York City hospitals <br>
•	Summarizes analytical methods, data analysis, and results into written report format <br>

**Transcendent Endeavors, New York, NY October 2017–August 2018** <br>
_Grants and Research Manager (February–August 2018)_ <br>
•	Managed an 8-week timeline for the development and submission of 3 NIH Small Business Innovation Research (SBIR) grant proposals to fund technologies that address challenges in public health and early childhood education <br>
•	Tracked and navigated grant proposal progress as well as ensured compliance with 4 active grants <br>
•	Managed a team of 3 members and trained them on all aspects of SBIR grant writing and proposal development <br>
•	Secured and maintained 15+ partnerships and collaborations with community-based organizations and health-focused nonprofit agencies in New York for grants and research activities <br>
•	Developed IRB protocols, consent forms, and surveys for 2 research site activities with local nonprofit organizations   <br>
 
_Grants and Research Fellow/Associate (October 2017–January 2018)_                                                   
•	Drafted 3 NIH SBIR grant proposals to fund web-based health technologies and mobile apps <br>
•	Gathered evidence-based research concerning best practices for population health challenges for underserved communities and current technology-based innovations <br>
•	Developed study materials, including surveys, flyers, and interview scripts; led participant interviews for product testing

**Association of Schools and Colleges of Optometry (ASCO), Rockville, MD, February 2017–May 2017** <br>
_Intern_ <br>
•	Conducted interviews with [pre-optometry students](https://optometriceducation.org/pre-optometry-clubs-with-brighter-visions-helping-their-campus-community-one-day-at-a-time/) and ASCO’s [president](https://optometriceducation.org/a-short-conversation-with-dr-david-damari-asco-president/) to write blog posts for Eye on Optometry <br>
•	Developed journal topics and [wrote articles](https://eye.opted.org/3758) for ASCO's online journal, Eye on Education <br>
•	Analyzed optometry school applicant data and utilized Excel to create visuals for the public

**Truth Initiative, Washington, D.C., September 2016–December 2016** <br>         _Youth Activism Intern_ <br>
•	Communicated with 54 representatives from 47 Historically Black Colleges and Universities to support their efforts toward becoming tobacco-free campuses, to improve their outreach strategies, and to teach them how to optimize social media platforms <br>
•	Created and hosted a webinar, entitled Strategies to Improve Outreach and Education on Your Campus, which focused on outreach and education practices as well as on tobacco as a social justice issue

**Monmouth County Mosquito Control, Eatontown, NJ, June 2016–August 2016** <br>
_Mosquito and Tick Public Health Intern_ <br>
•	Educated public over-the-phone and in-person about mosquito-borne diseases, tick-borne diseases, and bite prevention <br>
•	Organized and increased data entry for mosquito service requests and larvicide results

**DC Health Leads, Children’s National Medical Center, Washington, D.C., September 2014–December 2015** <br>
_Health Leads Advocate_ <br>
•	Connected low-income families with resources they need to remain healthy by “prescribing” resources such as food, housing, and heating assistance using Health Leads Reach technology <br>
•	Led on-campus peer discussion group to discuss client issues, new resources, and updates 

<br>

## PUBLIC HEALTH VOLUNTEER EXPERIENCE <br>
• **Camp Kesem GW,** _Program Counselor & Teen Camp Unit Leader,_ December 2014–August 2017 <br>
• **A Wider Circle,** _Intern (Public Health Program Development),_ September 2015–December 2015 <br>
• **Robert Wood Johnson University Hospital,** _Community Health Department Volunteer,_ June 2015–August 2015 <br>
• **The George Washington University Hospital,** _Internal Medicine/ Oncology Unit Volunteer,_ September 2014–May 2015 <br>
• **The Bristol-Myers Squibb Children’s Hospital,** _Pediatric Intensive Care Unit Volunteer,_ June 2014–August 2014 <br>
• **Robert Wood Johnson University Hospital,** _Pharmacy Department Volunteer,_ June 2014–August 2013 
 
<br>

## SKILLS 
**Software:** Microsoft Office, MS Access (relational database design and development), BioNumerics, SAS, R, SQL <br>
**Certifications:** HIPAA Patient Privacy and CITI Human Subjects Protection
